OUTPUT:
  DIRECTORY: output

DATA:
  RAW_DIRECTORY: data/raw
  INTERIM_DIRECTORY: data/interim
  PROCESSED_DIRECTORY: data/processed
  EXTERNAL_DIRECTORY: data/external

NOTEBOOKS:
  DIRECTORY: source/notebooks

MLFLOW:
  SERVER_URL: http://mlflow_server:1235
  CLIENT_URL: http://127.0.0.1:1235
  EXPERIMENT_NAME: credit
  MODEL_NAME: credit_model
