project: pytorch-demo-v2
tags:
  - pytorch
  - demo
notes: changed to out_channels and kernel_sizes
architecture: CNN
epochs: 40
out_channels:
  - 16
  - 32
kernel_sizes:
  - 3
  - 5
batch_size: 64
optimizer: adam
learning_rate: 0.01
num_reduce_learning_rate: 3  # we decrease the learning rate 5 times
