project: pytorch-demo
tags:
  - default
notes: default configuration for a fully connected network
architecture: FC
# experiment parameters
epochs: 40
batch_size: 64
optimizer: adam
learning_rate: 0.005
num_reduce_learning_rate: 3  # we decrease the learning rate 5 times
# model parameters
hidden_layers:
  - 500
  - 100
