project: pytorch-demo-v2
tags:
  - pytorch
  - demo
notes: First run with a simple CNN
architecture: CNN
epochs: 40
kernels:
  - 16
  - 32
batch_size: 64
optimizer: adam
learning_rate: 0.01
num_reduce_learning_rate: 3  # we decrease the learning rate 5 times
