project: pytorch-demo
tags:
  - pytorch
  - demo
notes: First run with a simple fully connected network
architecture: FC
epochs: 40
layers:
  - 500
  - 100
batch_size: 64
optimizer: adam
learning_rate: 0.005
num_reduce_learning_rate: 3  # we decrease the learning rate 5 times
